### ISSUE TITLE
Playground-iOS not compiling: "Extra argument 'height' in call"

### ISSUE THREAD

**Issue by dmcgloin** [zenangst/Family#105]
![Screen Shot 2019-04-27 at 7 13 04 PM](https://user-images.githubusercontent.com/457139/56857293-8b647f80-6920-11e9-8184-0d9e076ff413.png)

**Comment by zenangst** [comment]
Hey @dmcgloin, thanks for reporting this, I've simply forgotten to update the playground to reflect the latest version of the public API. However, if I do update it to the latest version there are still some underlying issues that cause the playgrounds to crash and debugging playgrounds is not a trivial task.

**Comment by dmcgloin** [comment]
Ahhh. Saw that too, @zenangst, after I tried to do the fix ups. Wasn't quite sure what was going on. Haven't actually used playgrounds that much. Was looking for some kind of demo to visualize what your framework offers. Is there an app out there that uses this so I could take a look? Thank you

**Comment by zenangst** [comment]
@dmcgloin hey mate, I finally figured it out, apparently, it is important in which order things are set up when using a playground. I made this PR to fix it #135

**Comment by zenangst** [comment]
@dmcgloin sorry for the huge delay here, it should be on `master` now :)
