### ISSUE TITLE
Crash on iOS 10 due to NSKeyValueObservation is not invalidated when deinit

### ISSUE THREAD

**Issue by superk589** [zenangst/Family#130]
The demo project to reproduce the crash is here
https://github.com/superk589/FamilyDemo
Also a pull request later.

**Comment by zenangst** [comment]
I’ll make a new release when I get back from vacation 😎

**Comment by zenangst** [comment]
@superk589 a new version is available on GitHub and a new version is being pushed to CocoaPods as I write this :)

**Comment by superk589** [comment]
@zenangst Thank you, updated 😊
