### ISSUE TITLE
UISelectionGrabberDot should not be wrapped by FamilyWrapperView

### ISSUE THREAD

**Issue by superk589** [zenangst/Family#166]
I found this bug when embedding a UITextView inside a UITableViewCell, then in a FamilyViewController.
UISelectionGrabberDot is a private type of UIKit, it represents the two pins on the two sides of the selected range.
<img width="125" alt="image" src="https://user-images.githubusercontent.com/19667784/69492251-fa1bb280-0eda-11ea-99ef-f71ff339ec33.png">

<img width="1273" alt="familydemo" src="https://user-images.githubusercontent.com/19667784/69492260-37804000-0edb-11ea-8bc5-5e01daf3c0dd.png">

This view is wrapped by FamilyWrapperView. And it causes some strange behavior such as an incorrect frame of the dot's first ancestor scroll view subclass, the UITextView.

**Comment by zenangst** [comment]
@superk589 interesting find, mind sharing some details of your view controller setup, how are you adding the textview to your view hierarchy ?

**Comment by superk589** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/19667784/69492406-7d3e0800-0edd-11ea-8f35-7ba3e08ab69b.png">

As simple as the image.
But I can't reproduce this bug in a clean demo. Still trying to find what's the difference between them.

**Comment by zenangst** [comment]
@superk589 keep me posted!

**Comment by superk589** [comment]
https://github.com/superk589/FamilyDemo
The newest commit can reproduce the bug.
Steps: 
1. Long press on a text view
2. Scroll down and you can see the pin is disappeared(only left the cursor here)
<img width="107" alt="image" src="https://user-images.githubusercontent.com/19667784/69492709-da878880-0ee0-11ea-9ba3-e802c9c85163.png">

**Comment by zenangst** [comment]
Mind testing this branch: `fix/selection-grabber-dot-being-added`

**Comment by superk589** [comment]
It has been fixed. Thank you! 👍

**Comment by zenangst** [comment]
Awesome! I merged it into master, will make a new version a little later. I’m currently traveling from Sweden to Norway. I’ll close the issue when the new version is out

**Comment by zenangst** [comment]
`0.22.7` has now been released and should be out on cocoa pods any minute now. Closing this issue now, thanks for reporting @superk589
