### ISSUE TITLE
View Reuse not working if there is more than one ChildViewController

### ISSUE THREAD

**Issue by richardtop** [zenangst/Family#2]
Hi Chris,
I've read the post on Medium and liked the idea of the project. After giving it a try, I found one bug: view reuse stops working if there is more than 1 ChildViewController.

For example, in case of adding a single `UITableViewController` the cells are reused correctly, their number never grows more than ±20.

However, after adding a second `UIViewController`, cell reuse stops working.

The problem is that the `ChildViewController`'s frame grows more than the window size. Also, the frame grows in the scroll direction (i.e. if I scroll down, there are more bottom cells than could be displayed on the screen).

I guess, the reason is because the `contentOffset` or `bounds` are added multiple times, I was not able to trace it quickly, but I hope this description might give you a hint on how to fix it.

**Screenshot of the bug:**
![image](https://user-images.githubusercontent.com/8013017/36480212-252452cc-1714-11e8-8670-830a0e7cb4b2.png)

**Project used to reproduce the bug**
[Family-master-bug-test.zip](https://github.com/zenangst/Family/files/1743987/Family-master-bug-test.zip)

The issue is present in both, _master_ and _feature/macos-support_ branches

**Comment by zenangst** [comment]
Hey @richardtop, long time no talk, I'll have a look to see what is going on! :)

**Comment by zenangst** [comment]
@richardtop hello again, I made a fix for this issue. Mind checking out #4 to see if that doesn't fix the issue.

**Comment by zenangst** [comment]
@richardtop  Thanks for the demo project btw, it helped a lot when reproducing and making a fix ❤️
